name: Auto assign project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign-project:
    runs-on: ubuntu-latest
    name: Assign project
    steps:
      - uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/cse110-sp21-group10/cse110-sp21-group10/projects/1'
#         column-name defaults to 'To Do' for issues and 'In Progress' for pull requests
