name: Generate JSDocs

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    name: Auto generate documentation from JSDocs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: /src
          recurse: true
          output_dir: /documentation
          template: minami
          front_page: README.md
