name: Generate JSDocs

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    name: Auto generate documentation from JSDocs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate documentation
        uses: codevise/documentation-js-action@v1
        with:
          input: ./src
          output: ./docs
          format: md
          projectName: Team 10 Bullet Journal
          projectVersion: 1
          projectDescription: bullet journal created using Agile princples for CSE 110
          projectHomepage: ./README.md
      
      - name: Documentation result
        run: ls ./docs
